
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # The database name will typically be <app_name>_development
  database: forja_development
  # Use environment variables for sensitive data

test:
  <<: *default
  database: forja_test

production:
  database: forja_production
  url: <%= ENV['DATABASE_URL'] %>
  # Alternatively, you can specify individual variables:
  # username: <%= ENV['PROD_DATABASE_USERNAME'] %>
  # password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
  #
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
